# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: exeshnik 1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "exeshnik".freeze
  s.version = "1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Svetlana Tarasova".freeze]
  s.date = "2020-09-30"
  s.email = "ahmadeeva.su@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "exeshnik.gemspec",
    "init.rb",
    "install",
    "lib/exeshnik.rb",
    "lib/exeshnik/config.rb",
    "lib/exeshnik/engine.rb",
    "lib/exeshnik/middleware.rb",
    "lib/exeshnik/rails/controller.rb",
    "lib/exeshnik/rails/controller/redirects.rb",
    "lib/exeshnik/rails/controller/url_rewriting.rb",
    "lib/exeshnik/rails/helpers.rb",
    "lib/exeshnik/rails/helpers/javascript_helper.rb",
    "lib/exeshnik/rails/helpers/url_helper.rb",
    "lib/exeshnik/user.rb"
  ]
  s.homepage = "http://github.com/ahmadeeva-su/exeshnik".freeze
  s.rubygems_version = "3.1.2".freeze
  s.summary = "EXE.RU api for Rails applications".freeze
end

