# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: exeshnik 0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "exeshnik"
  s.version = "0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Svetlana Tarasova"]
  s.date = "2018-01-16"
  s.email = "ahmadeeva.su@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "exeshnik.gemspec",
    "init.rb",
    "install",
    "lib/exeshnik.rb",
    "lib/exeshnik/config.rb",
    "lib/exeshnik/engine.rb",
    "lib/exeshnik/middleware.rb",
    "lib/exeshnik/rails/controller.rb",
    "lib/exeshnik/rails/controller/redirects.rb",
    "lib/exeshnik/rails/controller/url_rewriting.rb",
    "lib/exeshnik/rails/helpers.rb",
    "lib/exeshnik/rails/helpers/javascript_helper.rb",
    "lib/exeshnik/rails/helpers/url_helper.rb",
    "lib/exeshnik/user.rb"
  ]
  s.homepage = "http://github.com/ahmadeeva-su/exeshnik"
  s.rubygems_version = "2.5.1"
  s.summary = "EXE.RU api for Rails applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ie_iframe_cookies>, ["~> 0.1.2"])
    else
      s.add_dependency(%q<ie_iframe_cookies>, ["~> 0.1.2"])
    end
  else
    s.add_dependency(%q<ie_iframe_cookies>, ["~> 0.1.2"])
  end
end

